### ISSUE TITLE
Utility of `XXX_change_file` ?

### ISSUE THREAD

**Issue by TanguyBarthelemy** [rjdemetra/rjd3providers#23]
In which context `XXX_change_file` is useful ?
These functions (for spreadsheet and txt) are working with a path formatted with java format and not user friendly.

Maybe adding a `URLencode()` call inside will solve this problem ?

**Comment by AQLT** [comment]
They can for example be used to update the path of your file

**Comment by TanguyBarthelemy** [comment]
Yes but the needed format `C%3A%5CUsers%5CProjects+R%5C...` is complicated for the users?

**Comment by AQLT** [comment]
Ok you mean the `id` parameter? You can get it with the function `rjdemetra3::.jsa_ts_metadata(jsa, "@id")`
